budgets/urls.py
from django.urls import path
from .views import (
    BudgetView,
    UserHomeView,
    AddTransactionView,
    GetCategoriesView,
    HomeView,
    AddBudgetView,
    BudgetEditView,
    BudgetDeleteView,
    CatagoryDetail,
    CategoryEditView,
    CategoryDeleteView,
    SetIncome,
    DeleteTransactionView,
    EditTransactionView,
    TransactionView,
    SearchResultsView,
)

urlpatterns = [
    path("user/", UserHomeView.as_view(), name="user_home"),
    path("budget<int:pk>/", BudgetView.as_view(), name="budget"),
    path("add_transaction/", AddTransactionView.as_view(), name="add_transaction"),
    path("get_categories/", GetCategoriesView.as_view(), name="get_categories"),
    path("", HomeView.as_view(), name="home"),
    path("add_budget/", AddBudgetView.as_view(), name="add_budget"),
    path("<int:pk>/edit_budget/", BudgetEditView.as_view(), name="budget_edit"),
    path("<int:pk>/delete_budget/", BudgetDeleteView.as_view(), name="budget_delete"),
    path("<int:pk>/category/", CatagoryDetail.as_view(), name="category_detail"),
    path("<int:pk>/edit_category/", CategoryEditView.as_view(), name="category_edit"),
    path(
        "<int:pk>/delete_category/",
        CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path("<int:pk>/set_income/", SetIncome.as_view(), name="set_income"),
    path(
        "<int:pk>/delete_transaction/",
        DeleteTransactionView.as_view(),
        name="delete_transaction",
    ),
    path(
        "<int:pk>/edit_transaction/",
        EditTransactionView.as_view(),
        name="edit_transaction",
    ),
    path(
        "<int:pk>/transactions/", TransactionView.as_view(), name="budget_transactions"
    ),
    path("search/", SearchResultsView.as_view(), name="search_results"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("budgets.urls")),
]

budgets/models.py
from django.db import models
from djmoney.models.fields import MoneyField
from datetime import date
from django.urls import reverse
from django.conf import settings

# Create your models here.


class Budget(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    name = name = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("budget", kwargs={"pk": self.pk})


class Category(models.Model):
    budget = models.ForeignKey(
        "Budget",
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    amount_budgeted = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency="USD",
        null=True,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"pk": self.pk})


class Transaction(models.Model):
    merchant = models.CharField(max_length=255)
    amount = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency="USD",
    )
    date = models.DateField(default=date.today)
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
    )
    budget = models.ForeignKey(
        "Budget",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.merchant} {self.amount}"


class Income(models.Model):
    budget = models.ForeignKey(
        "Budget",
        on_delete=models.CASCADE,
    )
    monthly_income = MoneyField(
        max_digits=14, decimal_places=2, default_currency="USD", null=True, default=0
    )

    def __str__(self):
        return str(self.monthly_income)

templates/add_budget.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }
    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">{% csrf_token %}
        <h1>Add a Budget</h1>
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Create Budget</button>
    </form>
</div>
{% endblock content %}

templates/add_transaction.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">
        <h1>Add a new Transaction</h1>
        {% csrf_token %}
        <style type="text/css">
            #id_amount_1 {
                display: none;
            }
        </style>

        {{ form|crispy }}

        <button class="btn btn-success" type="submit">Add Expense</button>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        // Disable the category select initially
        $('#id_category').prop('disabled', true);

        $('#id_budget').change(function () {
            var budgetId = $(this).val();

            // Fetch categories based on the selected budget
            if (budgetId) {
                $.ajax({
                    url: '/get_categories/',
                    data: {
                        'budget_id': budgetId
                    },
                    success: function (data) {
                        // Enable the category select
                        $('#id_category').prop('disabled', false);

                        // Clear previous options
                        $('#id_category').empty();

                        // Add new options
                        $.each(data, function (key, value) {
                            $('#id_category').append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            } else {
                // If no budget is selected, clear and disable the category select
                $('#id_category').empty().prop('disabled', true);
            }
        });
    });
</script>
{% endblock content %}

templates/base.html
<!-- templates/base.html -->
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--Bootstrap-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <title>{% block title %}Budgify{% endblock title %}</title>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    {% if user.is_authenticated %}
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'user_home' %}">
        <img src="{% static '/images/79365.png' %}" alt="logo-image" width="30" height="30"
          class="d-inline-block align-text-top">
        Budgify
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'user_home' %}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">{{ user.username }}</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
          </li>
          <form class="d-flex" method="get" action="{% url 'search_results' %}">
            <input class="form-control me-2" name="q" type="search" placeholder="Find a budget" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </ul>
        <form class="d-flex">
          <button class="btn btn-success" type="submit">
            <a href="{% url 'add_transaction' %}" style="color:inherit; text-decoration: none;">Add Transaction</a>
          </button>
        </form>
      </div>
      {% else %}
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static '/images/79365.png' %}" alt="logo-image" width="30" height="30"
            class="d-inline-block align-text-top">
          Budgify
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Not Logged In</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'login' %}">Log In</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
      {% endif %}
  </nav>
</head>

<body>
  <main>
    <div class="page content-wrapper">
      {% if user.is_authenticated %}
      {% endif %}
      {% block content %}
      {% endblock content %}
    </div>
  </main>
  <!--Bootstrap-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</body>

</html>

templates/budget_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">{% csrf_token %}
        <h1>Are you sure you want to delete "{{ object.name }}"?</h1>
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Confirm</button>
    </form>
</div>
{% endblock content %}

templates/budget_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }

    .flex-container {
        display: flex;
    }
</style>

<div class="flex-container">
    <div class="containerBudget">
        <div class="dropdown float-right dropdown-container">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Budget Options
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'budget' budget.pk %}">View Budget</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'set_income' income.pk %}">Set Income</a>
                <a class="dropdown-item" href="{% url 'budget_edit' budget.pk %}">Edit Budget Name</a>
                <a class="dropdown-item" href="{% url 'budget_delete' budget.pk %}">Delete Budget</a>
                <a class="dropdown-item" href="{% url 'budget_transactions' budget.pk %}">View Transactions</a>
            </div>
        </div>
        <h2>{{ object.name }}</h2>
        <hr class="rounded">
        </br>

        {% if over_budgeted %}
        <div class="warning-box">Your planned budget is {{ over_budgeted }} over your income</div>
        <hr class="solid">
        {% endif %}

        {% if under_budgeted %}
        <div class="success-box">Your planned budget is {{ under_budgeted }} under your income</div>
        <hr class="solid">
        {% endif %}

        {% if at_budget %}
        <div class="success-box">Congratulations, Your planned budget perfectly matches your income</div>
        <hr class="solid">
        {% endif %}


        {% if income %}
        <div class="container-amount">
            <h4>Monthly Income:</h4>
            <div class="item-container-amount">
                <h4>{{ income.monthly_income }}</h4>
            </div>
        </div>

        {% else %}
        <p>No income data available.</p>
        {% endif %}
        <hr class="solid">

        <div class="container-amount">
            <h4>Total Spent:</h4>
            <div class="item-container-amount">
                <h4>{{ total_spent }}</h4>
            </div>
        </div>
        <hr class="solid">

        {% for category in categories %}
        <div class="container-amount">
            <h4>Category:</h4>
            <div class="item-container-amount">
                <h4>{{ category.name }}</h4>
            </div>
        </div>
        <div class="container-amount">
            <h6>Amount Budgeted:</h6>
            <div class="item-container-amount">
                <h6>{{ category.amount_budgeted }}</h6>
            </div>
        </div>
        <div class="container-amount">
            <h6>Amount Spent:</h6>
            <div class="item-container-amount">
                <h6>{{ category.amount_spent }}</h6>
            </div>
        </div>
        <a href="{% url 'category_detail' category.pk %}" class="btn btn-success btn-sm"
            style="color:inherit; padding-left: 10px; padding-right: 10px;">View Details</a>
        <hr class="solid">
        {% endfor %}
        <hr class="rounded">

        <a href="{% url 'budget_transactions' budget.pk %}" class="btn btn-success btn-sm"
            style="color:inherit; padding-left: 10px; padding-right: 10px;">Transactions</a>
        </br>
        <form action="" method="post">{% csrf_token %}
            <style type="text/css">
                #id_amount_budgeted_1 {
                    display: none;
                }
            </style>
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Add Category</button>
        </form>
    </div>
    <div class="containerBudgetGraph" data-monthly-income="{{ income.monthly_income.amount }}"
        data-total-spent="{{ total_spent.amount }}">
        <div>
            <canvas id="myDoughnutChart" width="400" height="400"></canvas>
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                // Get the context of the canvas element we want to select
                var ctx = document.getElementById('myDoughnutChart').getContext('2d');

                // Get the containerBudget div
                var containerBudget = document.querySelector('.containerBudgetGraph');

                // Parse data attributes to numbers
                var monthlyIncome = parseFloat(containerBudget.dataset.monthlyIncome);
                var totalSpent = parseFloat(containerBudget.dataset.totalSpent);

                // Calculate spent percentage
                var spentPercentage = (totalSpent / monthlyIncome) * 100;
                spentPercentage = Math.min(spentPercentage, 100);

                // Create the doughnut chart
                var myDoughnutChart = new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: ['Remaining Budget', 'Total Spent'],
                        datasets: [{
                            data: [100 - spentPercentage, spentPercentage],
                            backgroundColor: ['white', 'green'],
                            borderWidth: 2,
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        tooltips: {
                            callbacks: {
                                label: function (tooltipItem, data) {
                                    var label = data.labels[tooltipItem.index];
                                    var value = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];

                                    // Format tooltip value as dollar amount
                                    if (label === 'Total Spent') {
                                        return label + ': $' + totalSpent.toFixed(2);
                                    } else {
                                        return label + ': $' + ((monthlyIncome - totalSpent) || 0).toFixed(2);
                                    }
                                }
                            }
                        }
                    }
                });
            });
        </script>
    </div>
</div>
{% endblock content %}

templates/category_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">{% csrf_token %}
        <h1>Are you sure you want to delete "{{ object.name }}"?</h1>
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Confirm</button>
    </form>
</div>
{% endblock content %}

templates/category_detail.html
{% extends "base.html" %}

{% block content %}
<style>
    .flex-container {
        display: flex;
    }
</style>
<a href="{% url 'budget' object.budget.pk %}" class="btn btn-success btn-sm"
    style="color:inherit; padding-left: 10px; padding-right: 10px;">Back to {{ object.budget.name }}</a>
<div class="flex-container">
    <div class="containerBudget">
        <div class="dropdown float-right dropdown-container">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Category Options
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'category_detail' category.pk %}">View Category</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'category_edit' category.pk %}">Edit Category</a>
                <a class="dropdown-item" href="{% url 'category_delete' category.pk %}">Delete Category</a>
            </div>
        </div>
        <h2>{{ object.name }}</h2>
        <hr class="rounded">
        </br>
        <div class="container-amount">
            <h4>Amount Budgeted:</h4>
            <div class="item-container-amount">
                <h4>{{ object.amount_budgeted }}</h4>
            </div>
        </div>
        <hr class="solid">
        <div class="container-amount">
            <h4>Amount Spent:</h4>
            <div class="item-container-amount">
                <h4>{{ object.amount_spent }}</h4>
            </div>
        </div>
        <hr class="solid">
        </br>
        <h4>Transactions</h4>
        <hr class="rounded">
        {% for transaction in transactions %}
        <div class="containerBudget">
            <div class="container-amount">
                <h6>Merchant:</h6>
                <div class="item-container-amount">
                    <h6>{{ transaction.merchant }}</h6>
                </div>
            </div>
            <hr class="solid">
            <div class="container-amount">
                <h6>Amount:</h6>
                <div class="item-container-amount">
                    <h6>{{ transaction.amount }}</h6>
                </div>
            </div>
            <hr class="solid">
            <a href="{% url 'delete_transaction' transaction.pk %}" class="btn btn-success btn-sm"
                style="color:inherit; padding-left: 10px; padding-right: 10px;">Delete Transaction</a>
            </br>
            <a href="{% url 'edit_transaction' transaction.pk %}" class="btn btn-success btn-sm"
                style="color:inherit; padding-left: 10px; padding-right: 10px;">Edit Transaction</a>
            <hr class="solid">
        </div>
        {% endfor %}
    </div>
    <div class="containerBudgetGraph" data-monthly-income="{{ object.amount_budgeted.amount }}"
        data-total-spent="{{ object.amount_spent.amount }}">
        <div>
            <canvas id="myDoughnutChart" width="400" height="400"></canvas>
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                // Get the context of the canvas element we want to select
                var ctx = document.getElementById('myDoughnutChart').getContext('2d');

                // Get the containerBudget div
                var containerBudget = document.querySelector('.containerBudgetGraph');

                // Parse data attributes to numbers
                var monthlyIncome = parseFloat(containerBudget.dataset.monthlyIncome);
                var totalSpent = parseFloat(containerBudget.dataset.totalSpent);

                // Calculate spent percentage
                var spentPercentage = (totalSpent / monthlyIncome) * 100;
                spentPercentage = Math.min(spentPercentage, 100);

                // Create the doughnut chart
                var myDoughnutChart = new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: ['Remaining Budgeted', 'Total Spent'],
                        datasets: [{
                            data: [100 - spentPercentage, spentPercentage],
                            backgroundColor: ['white', 'green'],
                            borderWidth: 2,
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        tooltips: {
                            callbacks: {
                                label: function (tooltipItem, data) {
                                    var label = data.labels[tooltipItem.index];
                                    var value = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];

                                    // Format tooltip value as dollar amount
                                    if (label === 'Total Spent') {
                                        return label + ': $' + totalSpent.toFixed(2);
                                    } else {
                                        return label + ': $' + ((monthlyIncome - totalSpent) || 0).toFixed(2);
                                    }
                                }
                            }
                        }
                    }
                });
            });
        </script>
    </div>
</div>
{% endblock content %}

templates/category_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <style type="text/css">
            #id_amount_budgeted_1 {
                display: none;
            }
        </style>
        <button class="btn btn-success" type="submit">Update</button>
    </form>
</div>
{% endblock content %}

templates/category_list.html
{% extends "base.html" %}

{% block content %}
<p>{{ object.name }}</p>
<p>{{ object.amount_budgeted }}</p>
{% endblock content %}

templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<style>
    .functionality-image {
        width: 100%;
        height: auto;
    }

    .flex-containter {
        display: flex;
    }

    .heading {
        text-align: center;
    }

    .btn {
        margin: 0 5px;
        /* Adjust margin as needed */
    }
</style>
<div class="heading">
    <h1>Welcome, To Budgify</h1>
    <h5>The Future of Customized Budgetting</h5>
    <a href="{% url 'login' %}" class="btn btn-success btn-lg"
        style="color:inherit; padding-left: 10px; padding-right: 10px;">Log In</a>
    <a href="{% url 'signup' %}" class="btn btn-success btn-lg"
        style="color:inherit; padding-left: 10px; padding-right: 10px;">Sign Up</a>
</div>
<div class="flex-containter">
    <div class="containerBudget">
        <h2>All Your Budgets in One Place</h2>
        <img class="functionality-image" src="{% static '/images/Homepage.png' %}">
    </div>

    <div class="containerBudget">
        <h2>Create Customized Budgets Tailored to Your Needs</h2>
        <img class="functionality-image" src="{% static '/images/Budget.png' %}">
    </div>
</div>
<div class="flex-containter">
    <div class="containerBudget">
        <h2>Personalized Categories Automatically Update as You Add Transactions</h2>
        <img class="functionality-image" src="{% static '/images/Categories2.png' %}">
    </div>

    <div class="containerBudget">
        <h2>View All Your Transactions to Better Understand Your Spending Habits</h2>
        <img class="functionality-image" src="{% static '/images/Transactions.png' %}">
    </div>
</div>
{% endblock content %}

templates/income_set.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">{% csrf_token %}
        <h1>Set Your Monthly Income</h1>
        {{ form|crispy }}
        <style type="text/css">
            #id_monthly_income_1 {
                display: none;
            }
        </style>
        <button class="btn btn-success" type="submit">Set</button>
    </form>
</div>
{% endblock content %}

templates/transaction_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    input {
        max-width: 40em;
    }
</style>
<div class="form-container">
    <form method="post">{% csrf_token %}
        <style type="text/css">
            #id_amount_1 {
                display: none;
            }
        </style>
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Update</button>
    </form>
</div>
{% endblock content %}

templates/transactions.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'budget' budget.pk %}" class="btn btn-success btn-sm"
    style="color:inherit; padding-left: 10px; padding-right: 10px;">Back to {{ budget.name }}</a>
<h2>Transactions</h2>
<hr class="solid">
{% for transaction in transactions %}
<div class="containerBudget">
    <div class="container-amount">
        <h4>Merchant:</h4>
        <div class="item-container-amount">
            <h4>{{ transaction.merchant }}</h4>
        </div>
    </div>
    <hr class="solid">
    <div class="container-amount">
        <h4>Amount:</h4>
        <div class="item-container-amount">
            <h4>{{ transaction.amount }}</h4>
        </div>
    </div>
    <hr class="solid">
    <div class="container-amount">
        <h4>Budget:</h4>
        <div class="item-container-amount">
            <h4>{{ transaction.budget }}</h4>
        </div>
    </div>
    <hr class="solid">
    <div class="container-amount">
        <h4>Category:</h4>
        <div class="item-container-amount">
            <h4>{{ transaction.category }}</h4>
        </div>
    </div>
    <hr class="solid">
    <div class="container-amount">
        <h4>Date:</h4>
        <div class="item-container-amount">
            <h4>{{ transaction.date }}</h4>
        </div>
    </div>
    <hr class="solid">
    <a href="{% url 'delete_transaction' transaction.pk %}" class="btn btn-success btn-sm"
        style="color:inherit; padding-left: 10px; padding-right: 10px;">Delete Transaction</a>
    </br>
    <a href="{% url 'edit_transaction' transaction.pk %}" class="btn btn-success btn-sm"
        style="color:inherit; padding-left: 10px; padding-right: 10px;">Edit Transaction</a>
    <hr class="solid">
</div>
{% endfor %}
{% endblock content %}